### ISSUE TITLE
Omission of final newline and ^ after rewriting .qif file

### ISSUE THREAD

**Issue by jrrk** [Kraymer/qifqif#25]
downstairs-study:Banking jrrk$ cp InformeA{,_old}.qif 
    downstairs-study:Banking jrrk$ qifqif InformeA.qif 
    Amount..: -186.30
    Payee...: PURCHASE - DOMESTIC, FALLOWFIELD, WILLOW BANK HOTEL 
    Memo....: ** 1466
    Category: travel
    ---
    Amount..: -5.50
    Payee...: PURCHASE - DOMESTIC, TOLL CHARGE, M6 TOLL
    Memo....: ** 1466
    Category: travel
    ---
    Amount..: -4.80
    Payee...: PURCHASE - DOMESTIC, TOLL CHARGE, M6 TOLL
    Memo....: ** 1466
    Category: travel
    ---
    Amount..: 38.23
    Payee...: PURCHASE DOMESTIC REFUND, CAMBRIDGE, MARKS & SPENCER
    Memo....: ** 1101
    Category: clothing
    ---
    downstairs-study:Banking jrrk$ diff InformeA{,_old}.qif 
    2d1
    < 
    25c24,25
    < Lclothing
    \ No newline at end of file
    ---
    > Lclothing
    > ^
    downstairs-study:Banking jrrk$ more InformeA.qif 
    !Type:CCard    

    D25/12/2014
    T-186.30
    PPURCHASE - DOMESTIC, FALLOWFIELD, WILLOW BANK HOTEL
    M** 1466
    Ltravel
    ^
    D25/12/2014
    T-5.50
    PPURCHASE - DOMESTIC, TOLL CHARGE, M6 TOLL
    M** 1466
    Ltravel
    ^
    D28/12/2014
    T-4.80
    PPURCHASE - DOMESTIC, TOLL CHARGE, M6 TOLL
    M** 1466
    Ltravel
    ^
    D30/12/2014
    T38.23
    PPURCHASE DOMESTIC REFUND, CAMBRIDGE, MARKS & SPENCER
    M** 1101
    Lclothing
    downstairs-study:Banking jrrk$

**Comment by Kraymer** [comment]
Thanks for reporting :star2:, a patch will be landing tonight.
I'm more concerned by the ``^`` than the newline which plays no role in the qif parsing.

ps: plz prepend 4 spaces to lines when copy/pasting console logs, thks!

**Comment by Kraymer** [comment]
can you pull see if it works for you?

**Comment by jrrk** [comment]
Malhëurêsement, il ne march plus ...
PS I don't have an easy way to add the 4 spaces you wanted.

downstairs-study:qifqif jrrk$ python qifqif.py ~/Documents/journaladd/Banking/InformeA.qif 
Traceback (most recent call last):
  File "qifqif.py", line 11, in <module>
    qifqif.main()
  File "/Users/jrrk/Downloads/qifqif/qifqif/__init__.py", line 245, in main
    transacs_orig = parse_file(lines, options=args)
  File "/Users/jrrk/Downloads/qifqif/qifqif/__init__.py", line 142, in parse_file
    field_id = line[0]
IndexError: string index out of range
downstairs-study:qifqif jrrk$ cat !$
cat ~/Documents/journaladd/Banking/InformeA.qif
!Type:CCard

D25/12/2014
T-186.30
PPURCHASE - DOMESTIC, FALLOWFIELD, WILLOW BANK HOTEL
M** 1466
Ltravel
^
D25/12/2014
T-5.50
PPURCHASE - DOMESTIC, TOLL CHARGE, M6 TOLL
M** 1466
Ltravel
^
D28/12/2014
T-4.80
PPURCHASE - DOMESTIC, TOLL CHARGE, M6 TOLL
M** 1466
Ltravel
^
D30/12/2014
T38.23
PPURCHASE DOMESTIC REFUND, CAMBRIDGE, MARKS & SPENCER
M** 1101
Lclothingdownstairs-study:qifqif jrrk$ echo $LANG
en_GB

**Comment by Kraymer** [comment]
sorry for that. pull again please.

> PS I don't have an easy way to add the 4 spaces you wanted.

no prob. SublimeText or notepad++ can be used for such edits. Dunno if an online text editor exist that handle it.

**Comment by jrrk** [comment]
It's working again. But there is still no final newline after the last ^. Call me old fashioned but there are certain line oriented tools that do not like that behaviour. Particularly as the syntax itself is line oriented.

**Comment by Kraymer** [comment]
You re right I ll add it.

**Comment by Kraymer** [comment]
done.
