### ISSUE TITLE
<TAB> Completion

### ISSUE THREAD

**Issue by pescortell** [Kraymer/qifqif#53]
Completion function is not working for me. When it comes to introduce the category and I press tab it just shifts the cursor as usually happens when pressing tab in a text editor. 

I am running the module on the Command Prompt of Windows 8. 

I tried hard to find the cause of the non-working function without success. I am inexperienced on Python and programming in general.

Thanks

**Comment by Kraymer** [comment]
I'll try importing pyreadline module first before readline in the next version, which hopefully will fix the problem on Windows.

**Comment by Kraymer** [comment]
- I just commited an attempt for a fix
can you try pulling the new code and try again?

- What is the content of your `.qifqif.json` file ?

**Comment by pescortell** [comment]
I tryed with the updated files, and it is still not working. 

Just to let you know I do a couple of prior steps to manage to make it work, because it gives errors related to characters:
1. Change X, tick and + symbol in the "__init__" file by X,Y,and ok. 
2. I run `chcp 65001` to change it to UTF-8. 
3. In my tests I create a new json file since it gives me an error otherwise. In the example below it is j.qifqif.json
```

{
    "draft": [
        "draft"
    ],
    "new1": [
        "CASH"
    ],
    "new2": [
        "non"
    ],
    "new3": [
        "google"
    ]
}
```

I managed to set-up an EXCEL spreadsheet that makes a good work assigning automatically the category based on key words. Nevertheless I am still interested on this, since I believe the process is less tedious and more efficient with QifQif. 

Thanks

**Comment by Kraymer** [comment]
> because it gives errors related to characters:

can you paste the related error msg ?

**Comment by Kraymer** [comment]
@flywire can you confirm that the version 0.6 works for you without needing to edit the code regarding the display of unicode chars like ✔ ? If so, what windows console program do you use ?

**Comment by Kraymer** [comment]
> In my tests I create a new json file since it gives me an error otherwise.

By default it is supposed to create a file at `C:\\Users\YOU\.qifqif.json`.
can you look if this file exist ? what is the error returned ?

**Comment by Kraymer** [comment]
@pescortell concerning the unicode problems with windows console, it is quite common, cf http://stackoverflow.com/questions/5419/python-unicode-and-the-windows-console/4637795#4637795
I suggest you install the *win-unicode-console* package and read https://github.com/Drekin/win-unicode-console#usage to see how activate the thing.

**Comment by pescortell** [comment]
Thanks for the advice. I will install the package and try. Will give you
feedback on the weekend.

**Comment by Kraymer** [comment]
> Change X, tick and + symbol in the "init" file by X,Y,and ok.

Just did something similar in 7671e594, unicode symbols brought too much complications on Windows
