### ISSUE TITLE
Add feature to categorise ALL transactions not just those re-occurring

### ISSUE THREAD

**Issue by jonbartlett** [Kraymer/qifqif#63]
Love this tool. Makes categorising re-occurring transactions much easier. 

I would like to be able to use this or something similar to categorise all my transactions. The way I envisage this to work is that another file defines your account structure (this can be exported from GNUCash). This file is read when partially entering account names for a transaction with auto-completion feature. The current functionality is almost there but currently the accounts available in the auto-completion only comes from the keyword matching file.

Let me know what you think?

**Comment by Kraymer** [comment]
Good idea.

I'd like to keep a single file to store categories/matchings but it could totally work by initializing the categories list from the exported csv accounts list. something like `qifqif -c my_accounts.csv`

**Comment by Kraymer** [comment]
I pushed on master branch, please read https://github.com/Kraymer/qifqif/wiki/qifacc
Reopen if there is a problem.

**Comment by Kraymer** [comment]
*[Version 0.7.0](https://github.com/Kraymer/qifqif/releases/tag/v0.7.0) with this fix has been just shipped and can be installed via pip*.
