### ISSUE TITLE
Add ability to recategorize based on config (or ignore existing QIF category)

### ISSUE THREAD

**Issue by KengaRU** [Kraymer/qifqif#66]
My bank exports credit card transactions in QIF format with two already existing categories - "expense" and "income". Then using qifqif on such an file, only applicable but unusable mode is "-a", because it asks on every single transaction to acknowledge existing category, or edit. 

It would be great to have switch to ignore existing categories and rewrite them based on qifqif config file and user input (if no match on config entries).

**Comment by Kraymer** [comment]
Make a lotta sense.

What do you think of adding an `[a]llways`choice to the `Edit 'xxx' category ?` question in audit mode ?
So you press `A` twice (one for each category present in file) then all transactions of file are processed directly in edit mode.

**Comment by Kraymer** [comment]
Forget that I'll probably just add a `--force` mode.

**Comment by KengaRU** [comment]
May be --ignore category1,category2,category3 and --ignoreall switches?

**Comment by Kraymer** [comment]
*[Version 0.7.0](https://github.com/Kraymer/qifqif/releases/tag/v0.7.0) with this fix has been just shipped and can be installed via pip*.
