### ISSUE TITLE
When auditing, provide option to only wait on unknown categories

### ISSUE THREAD

**Issue by ebridges** [Kraymer/qifqif#75]
When using `--audit-mode` it seems redundant to have to hit `enter` on every single transaction: if the transaction matches, then it should skip ahead to the next transaction where there is no category.

Glad to submit a PR if I can get a pointer or two on where to add this feature.

Thanks

**Comment by Kraymer** [comment]
If you're only interested by transactions that mismatch/with no category, why not use the `-force` flag (without `--audit-mode`)?

    -f, --force           discard transactions categories if not present in
                          configuration file. Repeat the flag (-ff) to force
                          editing of all transactions.

**Comment by ebridges** [comment]
Ah-ha, yes.  That's what I was looking for.  The description of that flag is misleading: saying that it would discard transactions was not what I thought I wanted.

Perhaps it would be more accurate to say:

> Scroll past transactions that have already been categorized, stopping at uncategorized transactions in order to apply a category to it.

If you'd like a PR to update the documentation for that (either as above or how you'd like), glad to do so.

**Comment by Kraymer** [comment]
Well, it does say that it discards categories, not transactions.

The `--audit` mode keeps transactions untouched and pause after each transaction asking for edit. Default choice is *No edit* so you can scroll through the file quickly by pressing `Enter`. Hence the name.
The `--force` mode differs not only on which transactions are paused. When stopping at a transaction with an unknown (as set by an external tool) category, the category is erased and you're immediately confronted to the *Edit category* prompt. So it's more aggressive.

I edited the description and hope it's clearer now.

**Comment by ebridges** [comment]
Fair enough -- thanks much!
