### ISSUE TITLE
Python 3

### ISSUE THREAD

**Issue by DancingQuanta** [Kraymer/qifqif#76]
Make this wonderful project compatible with python 3

**Comment by Kraymer** [comment]
Hi,

Thanks for the kind words.
I've created a branch for the python3 port at https://github.com/Kraymer/qifqif/tree/py3
It just passed the tests on my machine, would appreciate if you could checkout the branch and make feedbacks.

**Comment by Kraymer** [comment]
Merged.

**Comment by flywire** [comment]
@Kraymer Following 8a423e9 3affece 06d9a6d 9fc13cb README.md and docs need updating re python version.
