### ISSUE TITLE
Will not run under Windows because of readline dep

### ISSUE THREAD

**Issue by flywire** [Kraymer/qifqif#83]
Win7, qifqif 0.7.3

Appears dependencies not loaded (or unavailable).

```
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\user>path=C:\Python27\;C:\Python27\Scripts\;%path%

C:\Users\user>python
Python 2.7.16 (v2.7.16:413a49145e, Mar  4 2019, 01:37:19) [MSC v.1500 64 bit (AM
D64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> qifqif.py
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'qifqif' is not defined
>>>

C:\Users\user>python qifqif.py
python: can't open file 'qifqif.py': [Errno 2] No such file or directory

C:\Users\user>qifqif
Traceback (most recent call last):
  File "C:\Python27\Scripts\qifqif-script.py", line 11, in <module>
    load_entry_point('qifqif==0.7.3', 'console_scripts', 'qifqif')()
  File "c:\python27\lib\site-packages\pkg_resources\__init__.py", line 487, in l
oad_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "c:\python27\lib\site-packages\pkg_resources\__init__.py", line 2728, in
load_entry_point
    return ep.load()
  File "c:\python27\lib\site-packages\pkg_resources\__init__.py", line 2346, in
load
    return self.resolve()
  File "c:\python27\lib\site-packages\pkg_resources\__init__.py", line 2352, in
resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "c:\python27\lib\site-packages\qifqif\__init__.py", line 18, in <module>
    import six
ImportError: No module named six

C:\Users\user>
```

**Comment by Kraymer** [comment]
I have a Windows now at home, so I'll have a look at it

**Comment by courtens** [comment]
`readline` is not supported in Windows, but suggested module 'pyreadline' is. Except that ... the module `pyreadline`  has no attribute for `parse_and_bind`... 

I found this https://stackoverflow.com/questions/38755851/pyreadline-arbitrary-autocomplete-on-windows as possible workaround, but I would not know how to best integrand it into qifqif.py

**Comment by Gegot** [comment]
Ok I could not get qifqif to run using Python 3.7.4 for Windows or Python 2.7 for Windows but found a (somewhat round about) workaround by installing Windows Subsystem for Linux for Windows 10:
https://docs.microsoft.com/en-us/windows/wsl/install-win10
I chose Debian from the Microsoft Store, started the shell, and did
`sudo apt-get update`
`sudo apt-get python-pip`

Then installed qifqif using pip and it works fine now. 
One small issue I found was when I copy the downloaded qif file into the Debian home directory using Windows Explorer it doesn't show up in Debian shell for a while. My work around was create a symbolic link to a windows directory under /mnt/c from the home Debian home directory (screenshot below). 
<BR>
![debian](https://user-images.githubusercontent.com/58610626/71310541-0b24ea00-23db-11ea-9ed1-c3b8503235df.png)

**Comment by flywire** [comment]
This application uses `readline` for the user interface which is not fully supported by Python 3.8.1  under Win 10.

Quick and dirty fix to run:
1. `pip install pyreadline`
2. edit ui.py and replace `readline.parse_and_bind('tab: complete')` with `pass`
3. edit ui.py and replace all code in `def set_completer(options=None):` with `return None`

Changes generated in output file but no `.qifqif.json` file generated.

**Comment by Kraymer** [comment]
Please have a look at [latest release](https://github.com/Kraymer/qifqif/releases/tag/v0.8.0)
