### ISSUE TITLE
Will not run under Windows

### ISSUE THREAD

**Issue by kingslayer64** [Kraymer/qifqif#86]
I think I understand that qifqif isn't quite for Windows but I was hoping you could help.  I'm receiving the below error and I'm not sure why it's breaking.  Any thoughts?

py -2 -m qifqif
Traceback (most recent call last):
  File "C:\Python27\lib\runpy.py", line 163, in _run_module_as_main
    mod_name, _Error)
  File "C:\Python27\lib\runpy.py", line 111, in _get_module_details
    __import__(mod_name)  # Do not catch exceptions initializing package
  File "C:\Python27\lib\site-packages\qifqif\__init__.py", line 18, in <module>
    import six
ImportError: No module named six

**Comment by Kraymer** [comment]
Can you try installing the `prompt_toolkit` branch rather than the default one, hopfully it should work better on Windows.

Install is : `pip install -e git://github.com/Kraymer/qifqif.git@prompt_toolkit#egg=qifqif`

**Comment by kingslayer64** [comment]
Thanks for the assist.  
I realized the six error was because I didn't install the six package as outlined in your requirements.txt.  I'm still getting the below error after installing the prompt_toolkit.  Any idea's that you might have would be appreciated.  Thanks again.

py -2 -m qifqif
Traceback (most recent call last):
  File "C:\Python27\lib\runpy.py", line 163, in _run_module_as_main
    mod_name, _Error)
  File "C:\Python27\lib\runpy.py", line 111, in _get_module_details
    __import__(mod_name)  # Do not catch exceptions initializing package
  File "qifqif\__init__.py", line 25, in <module>
    from qifqif._version import __version__
ImportError: No module named _version

**Comment by Kraymer** [comment]
I commited a fix can you uninstall and then `pip install -e git://github.com/Kraymer/qifqif.git@prompt_toolkit#egg=qifqif` ?

**Comment by Kraymer** [comment]
Please have a look at [latest release](https://github.com/Kraymer/qifqif/releases/tag/v0.8.0)
